steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/supplyline-backend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/supplyline-backend:latest'
      - './backend'
    id: 'build-backend'

  # Build frontend image (initial build without backend URL)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/supplyline-frontend-temp:$BUILD_ID'
      - '--build-arg'
      - 'VITE_API_URL=PLACEHOLDER_BACKEND_URL'
      - './frontend'
    id: 'build-frontend-temp'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/supplyline-backend:$BUILD_ID'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Deploy backend to Cloud Run (without CORS initially)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'supplyline-backend-${_ENVIRONMENT}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/supplyline-backend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'FLASK_ENV=production,DB_HOST=/cloudsql/${_CLOUDSQL_INSTANCE},DB_USER=supplyline_user,DB_NAME=supplyline,PYTHONDONTWRITEBYTECODE=1,PYTHONUNBUFFERED=1'
      - '--set-secrets'
      - 'SECRET_KEY=supplyline-secret-key:latest,DB_PASSWORD=supplyline-db-password:latest'
      - '--set-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Get backend URL after deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the actual backend URL
        BACKEND_URL=$$(gcloud run services describe supplyline-backend-${_ENVIRONMENT} --region=${_REGION} --format="value(status.url)")
        echo "Backend URL: $$BACKEND_URL"
        echo "$$BACKEND_URL" > /workspace/backend_url.txt
    id: 'get-backend-url'
    waitFor: ['deploy-backend']

  # Build frontend with correct backend URL
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Read the backend URL
        BACKEND_URL=$$(cat /workspace/backend_url.txt)
        echo "Building frontend with backend URL: $$BACKEND_URL"

        # Build frontend with correct backend URL
        docker build \
          -t gcr.io/$PROJECT_ID/supplyline-frontend:$BUILD_ID \
          -t gcr.io/$PROJECT_ID/supplyline-frontend:latest \
          --build-arg VITE_API_URL=$$BACKEND_URL \
          ./frontend
    id: 'build-frontend'
    waitFor: ['get-backend-url']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/supplyline-frontend:$BUILD_ID'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'supplyline-frontend-${_ENVIRONMENT}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/supplyline-frontend:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '0.5'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

  # Update backend CORS configuration with actual frontend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the actual frontend URL
        FRONTEND_URL=$$(gcloud run services describe supplyline-frontend-${_ENVIRONMENT} --region=${_REGION} --format="value(status.url)")
        BACKEND_URL=$$(cat /workspace/backend_url.txt)

        echo "Frontend URL: $$FRONTEND_URL"
        echo "Backend URL: $$BACKEND_URL"

        # Verify URLs are not empty
        if [ -z "$$FRONTEND_URL" ]; then
          echo "ERROR: Frontend URL is empty"
          exit 1
        fi

        if [ -z "$$BACKEND_URL" ]; then
          echo "ERROR: Backend URL is empty"
          exit 1
        fi

        # Update backend with correct CORS configuration
        echo "Updating backend CORS configuration..."
        gcloud run services update supplyline-backend-${_ENVIRONMENT} \
          --region=${_REGION} \
          --update-env-vars="FLASK_ENV=production,CORS_ORIGINS=$$FRONTEND_URL,DB_HOST=/cloudsql/${_CLOUDSQL_INSTANCE},DB_USER=supplyline_user,DB_NAME=supplyline,PYTHONDONTWRITEBYTECODE=1,PYTHONUNBUFFERED=1" \
          --set-secrets="SECRET_KEY=supplyline-secret-key:latest,DB_PASSWORD=supplyline-db-password:latest"

        echo "CORS configuration updated successfully"

        # Test backend health after CORS update
        echo "Testing backend health..."
        sleep 10  # Wait for service to update
        curl -f "$$BACKEND_URL/api/health" || echo "WARNING: Backend health check failed"
    id: 'update-backend-cors'
    waitFor: ['deploy-frontend']

  # Final verification step
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get service URLs
        FRONTEND_URL=$$(gcloud run services describe supplyline-frontend-${_ENVIRONMENT} --region=${_REGION} --format="value(status.url)")
        BACKEND_URL=$$(gcloud run services describe supplyline-backend-${_ENVIRONMENT} --region=${_REGION} --format="value(status.url)")

        echo "=== DEPLOYMENT VERIFICATION ==="
        echo "Frontend URL: $$FRONTEND_URL"
        echo "Backend URL: $$BACKEND_URL"
        echo ""

        # Test backend health
        echo "Testing backend health..."
        if curl -f "$$BACKEND_URL/api/health"; then
          echo "✅ Backend health check passed"
        else
          echo "❌ Backend health check failed"
          exit 1
        fi

        echo ""
        echo "=== DEPLOYMENT SUCCESSFUL ==="
        echo "Frontend: $$FRONTEND_URL"
        echo "Backend: $$BACKEND_URL"
        echo "Next steps:"
        echo "1. Test login with ADMIN001/admin123"
        echo "2. Verify CORS is working"
        echo "3. Check browser console for errors"
    id: 'verify-deployment'
    waitFor: ['update-backend-cors']

# Substitution variables
substitutions:
  _ENVIRONMENT: 'supplyline-beta'
  _REGION: 'us-west1'
  _CLOUDSQL_INSTANCE: 'gen-lang-client-0819985982:us-west1:supplyline-db'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/supplyline-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/supplyline-backend:latest'
  - 'gcr.io/$PROJECT_ID/supplyline-frontend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/supplyline-frontend:latest'
