#!/usr/bin/env python3
"""
Migration to add is_auto_generated column to user_requests table.

This column tracks whether a request was automatically generated by the system
(e.g., for chemical reordering) vs manually created by a user.
"""

import sys
from pathlib import Path

# Add parent directory to path so we can import app modules
sys.path.insert(0, str(Path(__file__).parent.parent))

from app import create_app
from models import db
from sqlalchemy import text


def migrate():
    """Add is_auto_generated column to user_requests table."""
    app = create_app()

    with app.app_context():
        # Check if column already exists
        result = db.session.execute(
            text("PRAGMA table_info(user_requests)")
        ).fetchall()
        column_names = [row[1] for row in result]

        if "is_auto_generated" in column_names:
            print("Column 'is_auto_generated' already exists in user_requests table.")
            return

        # Add the column
        print("Adding 'is_auto_generated' column to user_requests table...")
        db.session.execute(
            text("ALTER TABLE user_requests ADD COLUMN is_auto_generated BOOLEAN NOT NULL DEFAULT 0")
        )
        db.session.commit()
        print("Successfully added 'is_auto_generated' column to user_requests table.")


if __name__ == "__main__":
    migrate()
