directories:
  output: portable-build
  buildResources: build
appId: com.supplyline.mro-suite
productName: SupplyLine MRO Suite
copyright: Copyright © 2024 SupplyLine MRO Suite
files:
  - filter:
      - electron/**/*
      - frontend/dist/**/*
      - '!backend/**/*'
extraResources:
  - from: backend
    to: backend
    filter:
      - '**/*'
      - '!venv/**/*'
      - '!__pycache__/**/*'
      - '!*.pyc'
      - '!app.db'
      - '!database.db'
      - '!app.log'
      - '!error.log'
      - '!test_*.py'
      - '!tests/**/*'
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
  publisherName: SupplyLine MRO Suite
  verifyUpdateCodeSignature: false
  certificateFile: ''
  certificatePassword: <stripped sensitive data>
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: assets/icon.icns
  category: public.app-category.business
linux:
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
  icon: assets/icon.png
  category: Office
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  allowElevation: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: SupplyLine MRO Suite
dmg:
  title: SupplyLine MRO Suite ${version}
  icon: assets/icon.icns
  background: build/dmg-background.png
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
portable:
  artifactName: SupplyLine-MRO-Suite-${version}-portable.exe
publish:
  provider: github
  owner: PapaBear1981
  repo: SupplyLine-MRO-Suite
electronVersion: 32.3.3
