name: Nightly Quality Gates

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

env:
  PYTHONDONTWRITEBYTECODE: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  mutation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Mutation testing
        run: make mutate
      - uses: actions/upload-artifact@v4
        with:
          name: mutmut-nightly
          path: artifacts/mutmut
        if: always()

  k6-soak:
    runs-on: ubuntu-latest
    needs: mutation
    steps:
      - uses: actions/checkout@v4
      - name: Run k6 soak
        uses: grafana/k6-action@v0.3.1
        with:
          filename: qa/k6/checkin_soak.js
        env:
          K6_BASE_URL: https://api.example.com
          K6_TOKEN: test-token
          K6_DRY_RUN: "1"
